from .starship import Starship


EveOnline = [
    Starship("Heron", 35, "EVE Online"),
    Starship("Minmatar Shuttle", 24, "EVE Online"),
    Starship("Amar Shuttle", 33, "EVE Online"),
    Starship("Vigil", 24, "EVE Online"),
    Starship("Maulus", 37, "EVE Online"),
    Starship("Tormentor", 42, "EVE Online"),
    Starship("Velator", 37, "EVE Online"),
    Starship("Tormentor", 42, "EVE Online"),
    Starship("Bantam", 49, "EVE Online"),
    Starship("Slasher", 47, "EVE Online"),
    Starship("Executioneer", 50, "EVE Online"),
    Starship("Magnatte", 48, "EVE Online"),
    Starship("Galente Shuttle", 52, "EVE Online"),
    Starship("Tristan", 52, "EVE Online"),
    Starship("Griffin", 62, "EVE Online"),
    Starship("Slicer", 54, "EVE Online"),
    Starship("Rifter", 58, "EVE Online"),
    Starship("Concord Frigate", 60, "EVE Online"),
    Starship("Rifter", 58, "EVE Online"),
    Starship("Merlin", 64, "EVE Online"),
    Starship("Comet", 64, "EVE Online"),
    Starship("Reaper", 63, "EVE Online"),
    Starship("Hookbill", 70, "EVE Online"),
    Starship("Ibis", 64, "EVE Online"),
    Starship("Condor", 64, "EVE Online"),
    Starship("Caldari Shuttle", 66, "EVE Online"),
    Starship("Burst", 77, "EVE Online"),
    Starship("Punisher", 65, "EVE Online"),
    Starship("Impairor", 75, "EVE Online"),
    Starship("Navitas", 68, "EVE Online"),
    Starship("Inquisitor", 80, "EVE Online"),
    Starship("Probe", 73, "EVE Online"),
    Starship("Kestrel", 78, "EVE Online"),
    Starship("Incursus", 81, "EVE Online"),
    Starship("Catalyst", 87, "EVE Online"),
    Starship("Breacher", 111, "EVE Online"),
    Starship("Crusifier", 112, "EVE Online"),
    Starship("Augoror", 144, "EVE Online"),
    Starship("Concord Cruiser", 162, "EVE Online"),
    Starship("Maller", 185, "EVE Online"),
    Starship("Celestis", 124, "EVE Online"),
    Starship("Rupture", 167, "EVE Online"),
    Starship("Vexor", 206, "EVE Online"),
    Starship("Cormorant", 209, "EVE Online"),
    Starship("Bellicose", 230, "EVE Online"),
    Starship("Stabber", 240, "EVE Online"),
    Starship("Blakbird", 225, "EVE Online"),
    Starship("Scythe", 234, "EVE Online"),
    Starship("Coercer", 278, "EVE Online"),
    Starship("Thorax", 291, "EVE Online"),
    Starship("Thrasher", 300, "EVE Online"),
    Starship("Moa", 289, "EVE Online"),
    Starship("Omen", 292, "EVE Online"),
    Starship("Myrmidon", 311, "EVE Online"),
    Starship("Arbitrator", 327, "EVE Online"),
    Starship("Prophecy", 328, "EVE Online"),
    Starship("Osprey", 338, "EVE Online"),
    Starship("Brutix", 367, "EVE Online"),
    Starship("Iteron I", 364, "EVE Online"),
    Starship("Caracal", 385, "EVE Online"),
    Starship("Hoarder", 381, "EVE Online"),
    Starship("Exequror", 412, "EVE Online"),
    Starship("Harbringer", 395, "EVE Online"),
    Starship("Badger", 414, "EVE Online"),
    Starship("Scorpion", 452, "EVE Online"),
    Starship("Ferox", 452, "EVE Online"),
    Starship("Hurricane", 486, "EVE Online"),
    Starship("Cygil", 468, "EVE Online"),
    Starship("Cyclone", 496, "EVE Online"),
    Starship("Badger Mark II", 600, "EVE Online"),
    Starship("Drake", 514, "EVE Online"),
    Starship("Bestower", 683, "EVE Online"),
    Starship("Raven", 726, "EVE Online"),
    Starship("Tempest", 996, "EVE Online"),
    Starship("Dominix", 886, "EVE Online"),
    Starship("Rokh", 1007, "EVE Online"),
    Starship("Megathron", 1017, "EVE Online"),
    Starship("Obelisk", 1034, "EVE Online"),
    Starship("Armageddon", 1047, "EVE Online"),
    Starship("Iteron V", 1097, "EVE Online"),
    Starship("Abaddon", 1243, "EVE Online"),
    Starship("Mammoth", 1261, "EVE Online"),
    Starship("Naglfar", 1349, "EVE Online"),
    Starship("Maelstorm", 1481, "EVE Online"),
    Starship("Apocalypse", 1608, "EVE Online"),
    Starship("Hyperion", 1700, "EVE Online"),
    Starship("Concord Battleship", 1744, "EVE Online"),
    Starship("Fenrir", 1904, "EVE Online"),
    Starship("Thanatos", 2268, "EVE Online"),
    Starship("Charon", 2426, "EVE Online"),
    Starship("Providence", 2475, "EVE Online"),
    Starship("Chimera", 2560, "EVE Online"),
    Starship("Wyvern", 3187, "EVE Online"),
    Starship("Moros", 3207, "EVE Online"),
    Starship("Archon", 3255, "EVE Online"),
    Starship("Nyx", 3300, "EVE Online"),
    Starship("Phoenix", 3427, "EVE Online"),
    Starship("Revelation", 3791, "EVE Online"),
    Starship("Nidhoggur", 4027, "EVE Online"),
    Starship("Hel", 4268, "EVE Online"),
    Starship("Aeon", 5509, "EVE Online"),
    Starship("Avatar", 13774, "EVE Online"),
    Starship("Erebus", 14764, "EVE Online"),
    Starship("Ranarok", 18127, "EVE Online"),
]
