from .starship import Starship


Halo = [
    Starship("ODST Drop Pod", 2.3, "Halo"),
    Starship("Banshee", 7, "Halo"),
    Starship("Hornet", 9.6, "Halo"),
    Starship("Scape Pod", 10.4, "Halo"),
    Starship("Falcon", 11, "Halo"),
    Starship("Sabre", 23, "Halo"),
    Starship("UNSC Pelican", 30, "Halo"),
    Starship("Phantom", 32.5, "Halo"),
    Starship("Spirit", 33, "Halo"),
    Starship("Cryptum", 41, "Halo"),
    Starship("Longsword", 64, "Halo"),
    Starship("Light Cruiser", 300, "Halo"),
    Starship("In Amber Clad", 478, "Halo"),
    Starship("Destroyer UNSC", 485, "Halo"),
    Starship("Forward Unto Dawn", 489.8, "Halo"),
    Starship("UNSC Frigate", 490, "Halo"),
    Starship("Savannah", 535, "Halo"),
    Starship("Strider", 575, "Halo"),
    Starship("Anchor 9", 721, "Halo"),
    Starship("Orbital Defense Platform", 754, "Halo"),
    Starship("Corvette", 956, "Halo"),
    Starship("Hopefull", 1000, "Halo"),
    Starship("Halcyon", 1170, "Halo"),
    Starship("Marathon", 1192, "Halo"),
    Starship("Autumn", 1495, "Halo"),
    Starship("Valiant", 1518, "Halo"),
    Starship("Destroyer Covenant", 1664, "Halo"),
    Starship("Covenant Battlecruiser", 1782, "Halo"),
    Starship("Spirit of Fire", 2500, "Halo"),
    Starship("Covenant Assault Carrier", 5346, "Halo"),
    Starship("UNSC Infinity", 5600, "Halo"),
    Starship("Keyship", 13120, "Halo"),
    Starship("Cradle", 13200, "Halo"),
    Starship("Long Night of Solace", 27000, "Halo"),
    Starship("Mantle's Approach", 371000, "Halo"),
    Starship("High Charity", 464000, "Halo"),
    Starship("Halo", 10000000, "Halo"),
    Starship("The Ark", 127530000, "Halo"),
]
