from .starship import Starship


StarGate = [
    Starship("Puddle Jamper", 8, "StarGate"),
    Starship("Dart", 10, "StarGate"),
    Starship("Ori Fighter", 13, "StarGate"),
    Starship("F-302", 14, "StarGate"),
    Starship("Tel'tak", 15, "StarGate"),
    Starship("X-301", 22, "StarGate"),
    Starship("Death Glider", 28, "StarGate"),
    Starship("Al'kesh", 35, "StarGate"),
    Starship("Traveler Generational", 150, "StarGate"),
    Starship("Prometheus", 195, "StarGate"),
    Starship("Asuran Cruiser", 200, "StarGate"),
    Starship("Ra Ship", 260, "StarGate"),
    Starship("Wraith Hives Cruiser", 600, "StarGate"),
    Starship("Daedalus Cruiser", 610, "StarGate"),
    Starship("Ha'Tak Cruiser", 700, "StarGate"),
    Starship("Destiny Seedship", 1000, "StarGate"),
    Starship("Daniel Jackson", 1000, "StarGate"),
    Starship("Ori Mothership", 1100, "StarGate"),
    Starship("Gadmeer Terraformer", 1100, "StarGate"),
    Starship("Replicator Mothership", 1240, "StarGate"),
    Starship("Beilskner", 1400, "StarGate"),
    Starship("O'Neil Battleship", 1500, "StarGate"),
    Starship("Lantean Cruiser", 2500, "StarGate"),
    Starship("Apophis Mothership", 3325, "StarGate"),
    Starship("Aurora Battleship", 3500, "StarGate"),
    Starship("Atlantis City", 3750, "StarGate"),
    Starship("Anubis Mothership", 5500, "StarGate"),
    Starship("Корабль-улей рейфов", 5500, "StarGate"),
    Starship("Hive Ship", 11000, "StarGate"),
]
