from .starship import Starship


StarWars = [
    Starship("T-47 Snowspeeder", 4.5, "StarWars"),
    Starship("ETA-2 Actis", 5.47, "StarWars"),
    Starship("TIE Fighter", 6, "StarWars"),
    Starship("TIE Droid", 6.3, "StarWars"),
    Starship("Droid Starfighter", 6.96, "StarWars"),
    Starship("Storm IV Twin Pod cloud car", 7, "StarWars"),
    Starship("TIE Bomber", 7.8, "StarWars"),
    Starship("Jedi Starfighter", 8, "StarWars"),
    Starship("TIE Advanced (Vader's TIE)", 9.2, "StarWars"),
    Starship("TIE Defender", 9.2, "StarWars"),
    Starship("TIE Interceptor", 9.6, "StarWars"),
    Starship("A wing", 9.6, "StarWars"),
    Starship("Naboo N-1 Fighter", 11, "StarWars"),
    Starship("E wing", 11, "StarWars"),
    Starship("X wing", 12, "StarWars"),
    Starship("Y wing", 12.5, "StarWars"),
    Starship("ARC 170", 14.5, "StarWars"),
    Starship("B wing", 16, "StarWars"),
    Starship("LAAT", 17.4, "StarWars"),
    Starship("T-4a Lambda", 20, "StarWars"),
    Starship("Slave", 21.5, "StarWars"),
    Starship("Scimitar", 26.5, "StarWars"),
    Starship("Millenium Falcon", 34, "StarWars"),
    Starship("Naboo Royal Starship", 76, "StarWars"),
    Starship("Rebel Transport GR-75", 90, "StarWars"),
    Starship("Radiant VII", 115, "StarWars"),
    Starship("CR90 Corvette", 126, "StarWars"),
    Starship("C-9979 landing craft", 149, "StarWars"),
    Starship("EF-76 Nebulon-B", 300, "StarWars"),
    Starship("Core Ship", 696, "StarWars"),
    Starship("Acclamator", 752, "StarWars"),
    Starship("Destroyer Victory II", 900, "StarWars"),
    Starship("MC80 Star Cruiser", 1200, "StarWars"),
    Starship("Venator", 1155, "StarWars"),
    Starship("Destroyer Imperial I", 900, "StarWars"),
    Starship("Interdictor", 900, "StarWars"),
    Starship("Droid Control Ship", 3170, "StarWars"),
    Starship("Bellator", 7200, "StarWars"),
    Starship("Mediator", 8500, "StarWars"),
    Starship("Arc Hammer", 9500, "StarWars"),
    Starship("Sovereign", 15000, "StarWars"),
    Starship("Eclipse", 17500, "StarWars"),
    Starship("Executor", 19000, "StarWars"),
    Starship("Death Star", 160000, "StarWars"),
    Starship("Death Star 2", 9000000, "StarWars"),
]
