from .starship import Starship


StarTrack = [
    Starship("Shuttle type 9", 8.5, "StarTrack"),
    Starship("Peregrine", 14, "StarTrack"),
    Starship("Delta Flyer", 15, "StarTrack"),
    Starship("Danube", 23, "StarTrack"),
    Starship("Jemhadar Fighter", 68, "StarTrack"),
    Starship("Bird of Pray", 110, "StarTrack"),
    Starship("Z'gaava", 110, "StarTrack"),
    Starship("Defiant", 120, "StarTrack"),
    Starship("Deadalus", 140, "StarTrack"),
    Starship("Oberth", 150, "StarTrack"),
    Starship("Centaur", 210, "StarTrack"),
    Starship("D-5", 210, "StarTrack"),
    Starship("NX", 225, "StarTrack"),
    Starship("Sydney", 235, "StarTrack"),
    Starship("Hermes", 242, "StarTrack"),
    Starship("Miranda", 243, "StarTrack"),
    Starship("Soyuz", 248, "StarTrack"),
    Starship("Ronulan Bird of Pray", 248, "StarTrack"),
    Starship("Curry", 272, "StarTrack"),
    Starship("Constitution", 289, "StarTrack"),
    Starship("Constitution II", 305, "StarTrack"),
    Starship("Constelation", 310, "StarTrack"),
    Starship("Olimpic", 320, "StarTrack"),
    Starship("Springfield", 325, "StarTrack"),
    Starship("Interpid", 344, "StarTrack"),
    Starship("Yeager", 346, "StarTrack"),
    Starship("K'Tinga", 349, "StarTrack"),
    Starship("Norway", 364, "StarTrack"),
    Starship("Galor", 368, "StarTrack"),
    Starship("Cheyenne", 394, "StarTrack"),
    Starship("Tholian Orb Waves", 400, "StarTrack"),
    Starship("Prometheus", 415, "StarTrack"),
    Starship("New Orleans", 425, "StarTrack"),
    Starship("Avenger", 425, "StarTrack"),
    Starship("Kelvin", 450, "StarTrack"),
    Starship("Nebula", 440, "StarTrack"),
    Starship("Akira", 464, "StarTrack"),
    Starship("Surak", 476, "StarTrack"),
    Starship("Excelsior", 511, "StarTrack"),
    Starship("Ambassador", 526, "StarTrack"),
    Starship("Sphere Borg", 600, "StarTrack"),
    Starship("D'Kyr", 600, "StarTrack"),
    Starship("D'Kora", 630, "StarTrack"),
    Starship("Galaxy", 643, "StarTrack"),
    Starship("Sobereign", 685, "StarTrack"),
    Starship("Andromeda Ascendant", 1301, "StarTrack"),
    Starship("Romulan D'deridex", 1353, "StarTrack"),
    Starship("Deep Space Nine", 1451, "StarTrack"),
    Starship("Fesarius", 2000, "StarTrack"),
    Starship("The Doomsday Machine", 2772, "StarTrack"),

    Starship("Enterprise NCC 1701", 289, "StarTrack"),
    Starship("Enterprise NCC 1701-D", 642, "StarTrack"),
    Starship("Romulan Star Empire", 1341, "StarTrack"),
    Starship("Borg Cube", 3000, "StarTrack"),

    Starship("Earth Spacedock", 4600, "StarTrack"),
    Starship("Immense", 8250, "StarTrack"),
    Starship("Varro Generational Ship", 9320, "StarTrack"),
    Starship("Narada", 9369, "StarTrack"),
    Starship("Voth City Ship", 9800, "StarTrack"),
    Starship("Whale Probe", 73500, "StarTrack"),
    Starship("V'ger Ship", 97500, "StarTrack"),
    Starship("Unicomplex", 600, "StarTrack", scale=3),
    Starship("Dyson's Sphere", 200, "StarTrack", scale=9),
    Starship("V'ger Cloud", 12200, "StarTrack", scale=9),
]
